### PR TITLE
Adding in server response codes. Handling unknown codes.

### PR DESCRIPTION
**Pull request by cmeister747**
No message for 524 response so a key error message appears rather than a server error message. Added in entry for a 524 response to prevent this.

### CODE REVIEW

**Comment by quinnj** [comment]
Hmmm.....I wonder if we should really support these kinds of "unofficial" server response codes. I think I'm ok with it, but I'd suggest we support the full suite of Cloudflare, nginx, etc. codes. Mind updating the pull request with the info [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare)?

**Comment by quinnj** [comment]
Thanks. Looks great.

**Comment by cmeister747** [comment]
Was thinking of going in and setting a case for when there's no error code so that a KeyError isn't produced. I'll go ahead and do that now!

**Comment by quinnj** [comment]
Thanks!

**Pull request merged**
